tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "error": "#ffb4ab",
                "on-primary-fixed": "#000000",
                "surface-container-lowest": "#03030a",
                "primary-fixed-dim": "#00b8cc",
                "outline": "#334155",
                "on-secondary-fixed-variant": "#002266",
                "on-primary-fixed-variant": "#004e57",
                "on-secondary-fixed": "#FFFFFF",
                "inverse-surface": "#E2E8F0",
                "surface-variant": "rgba(22, 22, 44, 0.4)",
                "on-tertiary-fixed": "#000000",
                "on-surface": "#E2E8F0",
                "secondary-fixed-dim": "#0044cc",
                "primary-fixed": "#00E5FF",
                "on-primary-container": "#00E5FF",
                "surface-container-highest": "#282846",
                "on-secondary": "#FFFFFF",
                "surface-container-high": "#1e1e38",
                "surface-tint": "#00E5FF",
                "on-surface-variant": "#8492A6",
                "tertiary-fixed-dim": "#28a476",
                "tertiary": "#34d399",
                "outline-variant": "rgba(255, 255, 255, 0.08)",
                "primary-container": "rgba(0, 229, 255, 0.1)",
                "surface-container": "#16162c",
                "tertiary-fixed": "#34d399",
                "surface-bright": "#16162c",
                "inverse-on-surface": "#070714",
                "on-tertiary-fixed-variant": "#003924",
                "primary": "#00E5FF",
                "on-secondary-container": "#8492A6",
                "surface": "#070714",
                "secondary": "#0055FF",
                "error-container": "#93000a",
                "secondary-fixed": "#0055FF",
                "on-background": "#E2E8F0",
                "on-error": "#690005",
                "inverse-primary": "#0055FF",
                "tertiary-container": "rgba(52, 211, 153, 0.1)",
                "surface-dim": "#05050f",
                "on-error-container": "#ffdad6",
                "surface-container-low": "#0a0a1a",
                "on-tertiary": "#070714",
                "secondary-container": "#1e1e38",
                "on-tertiary-container": "#34d399",
                "on-primary": "#070714",
                "background": "#070714"
            },
            "borderRadius": {
                "DEFAULT": "0rem",
                "lg": "0.125rem",
                "xl": "0.25rem",
                "full": "9999px"
            },
            "fontFamily": {
                "headline": ["Space Grotesk"],
                "body": ["Space Grotesk"],
                "label": ["Space Grotesk"],
                "mono": ["JetBrains Mono"],
                "brand": ["Orbitron"]
            }
        },
    },
}
